### ISSUE TITLE
Sourcegraph badge

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#104]
As seen in [pgrok](https://github.com/pgrok/pgrok), sourcegraph badge can be added into README.

```
[![Sourcegraph](https://img.shields.io/badge/view%20on-Sourcegraph-brightgreen.svg?style=for-the-badge&logo=sourcegraph)](https://sourcegraph.com/github.com/sadikkuzu/squiral)
```

[![Sourcegraph](https://img.shields.io/badge/view%20on-Sourcegraph-brightgreen.svg?style=for-the-badge&logo=sourcegraph)](https://sourcegraph.com/github.com/sadikkuzu/squiral)

**Comment by sadikkuzu** [comment]
[![](https://img.shields.io/pypi/v/squiral)](https://pypi.org/project/squiral/)[![made-with-python](https://img.shields.io/badge/Made%20with-Python-1f425f.svg)](https://www.python.org/)[![](https://img.shields.io/pypi/pyversions/squiral.svg)](https://pypi.org/project/squiral/)[![Downloads](https://pepy.tech/badge/squiral)](https://pepy.tech/project/squiral)<br/>[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/sadikkuzu/squiral/main.svg)](https://results.pre-commit.ci/latest/github/sadikkuzu/squiral/main)[![Python lint&test](https://github.com/sadikkuzu/squiral/actions/workflows/python-package.yml/badge.svg)](https://github.com/sadikkuzu/squiral/actions/workflows/python-package.yml)[![Publish Python Package](https://github.com/sadikkuzu/squiral/actions/workflows/python-publish.yml/badge.svg)](https://github.com/sadikkuzu/squiral/actions/workflows/python-publish.yml)<br/>[![Sourcegraph](https://img.shields.io/badge/view%20on-Sourcegraph-brightgreen.svg?style=for-the-badge&logo=sourcegraph)](https://sourcegraph.com/github.com/sadikkuzu/squiral)

**Comment by ayushmaanshrotriya** [comment]
will do

**Comment by jdorfman** [comment]
Love this. Let me know when it is up, and @sourcegraph will tweet a link to this project

**Comment by ayushmaanshrotriya** [comment]
cool. However not assigned yet

**Comment by sadikkuzu** [comment]
Thank you so much for your first contribution!
Without people like you submitting PRs, open source projects couldn't be run.
You rock, @ayushmaanshrotriya 🚀

**Comment by ayushmaanshrotriya** [comment]
great. thanks!

**Comment by jdorfman** [comment]
Tweet queued up. Thanks @sadikkuzu @ayushmaanshrotriya

**Comment by sadikkuzu** [comment]
Wow @jdorfman 🤩 
I really appreciate 🙏🏼 ✨ 
https://twitter.com/sourcegraph/status/1635346932104323076

**Comment by jdorfman** [comment]
@sadikkuzu I told you :)

**Comment by sadikkuzu** [comment]
Yeah, you definitely did:)) @jdorfman 🚀

**Comment by ayushmaanshrotriya** [comment]
really cool

**Comment by sadikkuzu** [comment]
For readers reading these messages, you can join @sourcegraph discord server: https://discord.gg/s2qDtYGnAE
