### ISSUE TITLE
Add community governance docs

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#125]
- [ ] Code of Conduct
- [ ] Contributing.md
- [ ] Issue Template
- [ ] PR Template

Based on https://analyzemyrepo.com/analyze/sadikkuzu/squiral#Governance analysis.

**Comment by ZhiyaoWen999** [comment]
Hello sadikkuzu,

I would like to contribute these community docs.

May I ask are there any specific formats and requirements for these files?

Zhiyao

**Comment by sadikkuzu** [comment]
Hi @ZhiyaoWen999 

Thank you for your interest in contributing to community governance documentation! I really appreciate your willingness to help.

In terms of formats and requirements for these files, I do have some general guidelines to ensure consistency and clarity:

1. **Code of Conduct**: Please ensure that the Code of Conduct is written in a clear and concise manner. You can use existing open-source project code of conducts as a reference. It should outline expected behavior and consequences for violations within our community.
2. **Contributing.md**: This document should provide guidance for contributors on how to get started, how to format their contributions, and any specific workflows or tools they should be aware of when contributing to our project. Feel free to check out examples from other open-source projects for inspiration.
3. **Issue Template**: The issue template should assist contributors in creating clear and informative issue reports. It should include fields for describing the problem, steps to reproduce it, expected behavior, actual behavior, and any additional context that might be relevant.
4. **PR Template**: The pull request template should guide contributors in providing essential information about their pull request, such as a brief description of the changes, related issues or feature requests, and any specific steps required for testing or reviewing the changes.

Additionally, it's a good practice to ensure that all documentation is written in plain, easy-to-understand language, and that it's inclusive and welcoming to all potential contributors.

Feel free to use any existing open-source project's documentation as a reference or inspiration, and adapt them to suit [**squiral**](https://github.com/sadikkuzu/squiral)'s specific needs. Once you have drafts ready, you can submit them as pull requests for review, and we'll work together to refine and merge them into our repository.

If you have any specific questions or need further guidance while working on these documents, please don't hesitate to reach out. I'm here to help and collaborate on making our community better.

Thank you again for your willingness to contribute!

Best regards,
@sadikkuzu

**Comment by ZhiyaoWen999** [comment]
Thank you.

Will do
