### ISSUE TITLE
Add contributors badge into README

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#141]
https://contrib.rocks/image?repo=sadikkuzu/squiral

As in https://github.com/yusufcanb/tlm/blob/0d90e608842cf1122b35fc76dc720166619e7330/README.md?plain=1#L122-L126

**Comment by georgescutelnicu** [comment]
Hello, I'd be happy to take on this!

Can you tell me if this looks the way you want it?

![Screenshot_12](https://github.com/sadikkuzu/squiral/assets/122637419/9eea577c-e601-4aff-a5e4-97bfb79fa1d0)

**Comment by sadikkuzu** [comment]
@georgescutelnicu hi, wow 🤩 this preview looks awesome!

Looking forward to seeing your profile pic in that contributors part.

Thanks in advance.

**Comment by sadikkuzu** [comment]
The badge can be seen in https://pypi.org/project/squiral/

![image](https://github.com/sadikkuzu/squiral/assets/23168063/06f0160e-d60a-456b-8d71-0b6b7fb1b14c)
