### ISSUE TITLE
Run "poetry update"

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#36]
https://github.com/sadikkuzu/squiral/blob/b152bf2242677b7765902dc6ce7eb2fa26df84d9/poetry.lock#L1-L339

**Comment by Super76xx** [comment]
This is what she ran on me it most certainly has the same trait. I am completely green I have read about a few things but essentially know zilch. I am 45 and didn't have the internet in my school work hen I graduate In 95.

**Comment by Super76xx** [comment]
Would I try and sneak that into her phone with a screenshot of us. Inside a folder of many picturssdwill be oblivious
