### ISSUE TITLE
Upgrade "flake8"

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#38]
https://github.com/sadikkuzu/squiral/blob/b139fafd9a0a05f45700673752806bbe8818ce6e/pyproject.toml#L16

from 4.0.1 to 5.0.4

https://github.com/sadikkuzu/squiral/blob/b139fafd9a0a05f45700673752806bbe8818ce6e/.pre-commit-config.yaml#L14

to 5.0.4 again

**Comment by sadikkuzu** [comment]
Related to #36

**Comment by Super76xx** [comment]
Read me
